### ISSUE TITLE
bug(hooks/key): Unable to unregister events

### ISSUE THREAD

**Issue by davorpa** [ELTITO310/nextjs#1]
### Problem

https://github.com/ELTITO310/nextjs/blob/5128be913512b8de9b8f9881f71cc8514488197e/components/hooks/key.js#L11-L21

Accessor returned by `useEffect` is not able to remove events since doesn't use the same handler reference added by the listener.

### Possible fix

```js
document.addEventListener('keypress', handle);
return () => document.removeEventListener('keypress', handle);
```

### Some literature about

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

**Comment by ELTITO310** [comment]
Oh very thanks
